-- PostgreSQL Schema for Document Indexing Service

-- ===============================================
-- 1. Custom Type Definition
-- ===============================================

-- Define the ENUM type for consistent job status.
CREATE TYPE index_status_type AS ENUM (
    'PENDING',
    'PROCESSING',
    'COMPLETED',
    'FAILED'
);


-- ===============================================
-- 2. Table A: documents (Source of Truth - SOT)
-- ===============================================
-- Stores the core identity and stable metadata of the documents.
CREATE TABLE documents (
    -- Internal Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relationship and Tracking Keys
    owner_id BIGINT NOT NULL, -- Assumes a separate 'owner' table exists
    correlation_id VARCHAR(64) NOT NULL UNIQUE, -- Unique ID used for Elasticsearch linking
    
    -- Content Identifiers
    content_hash CHAR(64) NOT NULL UNIQUE, -- SHA-256 hash for deduplication
    title VARCHAR(256),
    
    -- Metadata and Timestamps
    source_uri CHAR(2048), -- FIX: Comma added here
    doc_details JSONB, -- Optimized for flexible, queryable document metadata
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()

    -- Foreign Key Constraint (Referential Integrity)
    -- NOTE: FK on owner_id is commented out per previous instruction
    -- CONSTRAINT fk_owner
    --     FOREIGN KEY (owner_id)
    --     REFERENCES owner (id)
    --     ON DELETE RESTRICT 
);


-- ===============================================
-- 3. Table B: document_metadata (Job Tracking)
-- ===============================================
-- Stores the transient job state related to the indexing process.
CREATE TABLE document_metadata (
    -- Internal Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Linking Key and Status
    correlation_id VARCHAR(64) NOT NULL UNIQUE, -- Links to the SOT job ID
    index_status index_status_type NOT NULL, -- Uses the defined ENUM type
    
    -- Foreign Key Column (References documents.content_hash)
    doc_content_hash CHAR(64) NOT NULL, -- FIX: Explicitly named as doc_content_hash

    -- Foreign Key Constraint
    CONSTRAINT fk_document_content_hash
        FOREIGN KEY (doc_content_hash) -- References the new column
        REFERENCES documents (content_hash) 
        ON DELETE CASCADE 
);


-- ===============================================
-- 4. Indexing Strategy
-- ===============================================

-- Index on the SOT table for fast owner-based retrieval and ordering by creation time.
CREATE INDEX idx_documents_owner_time 
    ON documents (owner_id, create_time DESC);

-- Index on the Tracking table for the most common query: finding jobs by status.
CREATE INDEX idx_document_metadata_status 
    ON document_metadata (index_status);